# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90dc4ce80095446ae9ba2c763dd2d9717b0e469dce37a98456e30ebd8ea926be84aa9ad54b5eaa41683f3bac84bedeb39a133717b807526e3a6391e0c4538368

test:
  secret_key_base: cfe9267be6d20d73b94147e9aa1fdd2381c1588cf9f60249c13cb6d82352776848963bf3c605a0c2256a9d9dab6e29cf781f5fe0e996370011809ccc39aae133

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
